name: Dependaboja
description: Merge dependabot PRs to aggregated branches and sync the aggregated branches with master

inputs:
  merge_type:
    description: 'Way of merge to use for syncing: merge/rebase/squah. Default is "rebase"'
    required: false
    default: rebase
  committer_name:
    required: false
    default: dependaboja
  committer_email:
    required: false
    default: --
  disabled_pr_targets:
    description: Comma separated list of branches wich are not allowed to be a PR target for auto merge. Default is 'master,main'
    required: false
    default: master,main
  sync_with:
    description: Comma separated list of branches which should be merged to agregated dependency branches automatically. Default is 'master,main'
    required: false
    default: master,main
  fetch_depth:
    description: We need a deep fetch in order to merge. It limits the max value. Default is 0
    required: false
    default: 0
  create_aggregated_branches_if_missed:
    description: If an aggregated target branch is missed Dependaboja creates it. That should prevent dependabot from being stuck with errors on missed target branches.
    required: false
    default: true

outputs: {}

runs:
  using: composite
  steps:

# The action consists of two parts: for "pull_request" and for "push".
# If "push" happens, then all "pull_request" related steps are skipped,
# and vice versa.


#################################
#   Run on a pull request       #
#################################

# In this part of action we check if the workflow was triggered by a PR:
# If "YES" we invoke some checkings and try to merge.
# Otherwise we just skip all steps of this part.

    - name: Run on PR
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo This was a pull request! Try to merge it to the target branch automatically.

# Verify some properties of the PR and also check that the target branch is enabled for auto-merging
# For instance, by default we do not allow to automerge to "master"

    - name: Shoud merge the PR?
      id: shouldmergepr
      if: >- # Check if it's dependabot
        ${{
          github.event_name == 'pull_request'
          && github.actor == 'dependabot[bot]'
          && startsWith(github.head_ref, 'dependabot/')
        }}
      shell: bash
      env:
        DISABLED_TARGETS: ${{inputs.disabled_pr_targets}}
        BASE_REF: ${{github.base_ref}}
      run: | # Check if the branch is enabled
        readarray -d , -t MERGEREFS <<< "$DISABLED_TARGETS"
        ENABLED=1
        for REF in "${MERGEREFS[@]}"; do
          if [ "$REF" == "$BASE_REF" ]; then
            ENABLED=0
          fi
        done
        echo Do we merge?: $([ "$ENABLED" == 1 ] && echo yes || echo no)
        echo "::set-output name=shouldmerge::$ENABLED"

    # Well, we have figured out that we are not going to perform the merge.
    # Report about it to logs and skip all further steps.
    - name: Report skip branch
      if: ${{github.event_name == 'pull_request' && steps.shouldmergepr.outputs.shouldmerge != 1}}
      shell: bash
      run: echo "::notice::Skip this PR"

# Perform merge of the PR:

    - name: Merge the PR
      if: ${{steps.shouldmergepr.outputs.shouldmerge == 1}}
      shell: bash
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{github.token}}
      run: gh pr merge --auto --rebase "$PR_URL"



#################################
#   Run on a push event         #
#################################

# In this part of action we check if the workflow was triggered by a push event:
# If "YES" we invoke some checkings and try to sync updates with target branches.
# Otherwise we just skip all steps of this part.

    - name: Run on push
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: echo This was a push! Try to sync it with dependabot target branches.

    # If "merge_type" was configured incorrectly then fail the action.
    - name: Check merge type
      id: mergetype
      if: ${{ github.event_name == 'push' }}
      shell: bash
      env:
        TYPE: ${{inputs.merge_type}}
      run: |
        if [[ "$TYPE" != 'rebase' && "$TYPE" != 'merge' && "$TYPE" != 'squash' ]]; then
          echo "::error::Invalid merge_type: $TYPE"
          exit 1
        fi

# Check that we want to sync with the the branch that has triggered the event.
# For instance, by default we want to sync with "master" or "main".
# Puth to any other branch would be ignored.

    - name: Is it a branch to sync?
      id: shouldsync
      if: ${{ github.event_name == 'push' }}
      shell: bash
      env:
        BRANCHES_TO_SYNC: ${{inputs.sync_with}}
        REF_NAME: ${{github.ref_name}}
      run: |
        readarray -d , -t SYNCBRANCHES < <(printf "%s" "$BRANCHES_TO_SYNC")
        for BRANCH in "${SYNCBRANCHES[@]}"; do
          if [ "$BRANCH" == "$REF_NAME" ]; then
            echo "::set-output name=shouldsync::1"
          fi
        done

    # Well, we have figured out that it's not a branch that we want to sycn with.
    # Report about it to logs and skip all further steps.
    - name: Report skip branch
      if: ${{github.event_name == 'push' && steps.shouldsync.outputs.shouldsync != 1}}
      shell: bash
      run: echo "::notice::Skip this branch"

# Perform sync:

    - name: Show YQ version
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      run: |
        jq --version || echo "no-jq"
        yq --version || echo "no-yq"

    - name: Find dependabot config
      id: find_dependabot
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      run: |
        if [ -f ./.github/dependabot.yaml ]; then
          echo "::set-output name=ext::yaml"
        elif [ -f ./.github/dependabot.yml ]; then
          echo "::set-output name=ext::yml"
        else
          echo "::error::Cannot find dependabot config"
          exit 1
        fi

    - name: Deep clone
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      uses: actions/checkout@v2.4.0 # same as ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        fetch-depth: ${{inputs.fetch_depth}}


    - name: Configure git environment
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      env:
        NAME: ${{inputs.committer_name}}
        EMAIL: ${{inputs.committer_email}}
      run: |
        git config user.name "$NAME"
        git config user.email "$EMAIL"

    - name: Read dependabot config and sync target branches
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      env:
        CMD: ${{steps.mergetype.outputs.cmd}}
        DEPCONF: ./.github/dependabot.${{steps.find_dependabot.outputs.ext}}
        REF: ${{github.ref}}
        TYPE: ${{inputs.merge_type}}
        CREATE_IF_MISSED: ${{inputs.create_aggregated_branches_if_missed}}
      run: |
        TARGETS=($(yq e '[.updates[].["target-branch"]]|unique|.[]' "$DEPCONF"))
        for BRANCH in "${TARGETS[@]}"; do
          echo "::group::Syncing $BRANCH"
          if [ "$TYPE" == 'rebase' ]; then
            git checkout -b "$BRANCH" "origin/$BRANCH" && git rebase -X theirs "$REF" \
            || ("$CREATE_IF_MISSED" && git checkout -b "$BRANCH" "$REF")
          elif [ "$TYPE" == 'merge' ]; then
            git checkout -b "$BRANCH" "origin/$BRANCH" && git merge -X theirs "$REF" \
          || ("$CREATE_IF_MISSED" && git checkout -b "$BRANCH" "$REF")
          elif [ "$TYPE" == 'squash' ]; then
            git checkout -b "$BRANCH" "$REF"
            git merge --squash -X ours "origin/$BRANCH" \
            && if [ -n "$(git status --porcelain)" ]; then
              git commit --no-edit
            fi \
            || "$CREATE_IF_MISSED"
          else
            echo "::error::Invalid merge type: $TYPE"
            exit 1
          fi
          git push --force origin "$BRANCH"
          echo "Done with syncing $BRANCH"
          echo "::endgroup::"
        done

branding:
  icon: git-merge
  color: white
