name: dependaboja

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [deps/**]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependaboja:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Dependaboja
        uses: evoja/dependaboja@v.0/0.2
        with:
          disabled_pr_targets: dev,master
          sync_with: dev
